TotalCross/totalcross

- TotalCrossSDK/src/main/java/totalcross/xml/ContentHandler.java
- TotalCrossSDK/src/main/java/totalcross/xml/XmlReader.java
Adds AttritubeList to tagName.
> Adding AttributeList to tagName

- TotalCrossVM/builders/gcc-linux-arm/sdl/build.bat
- TotalCrossVM/builders/gcc-linux-arm/tcvm/build.bat
- TotalCrossVM/builders/gcc-posix/tcvm/build.bat
Adding bats to generate the .so files for linux and linux_arm
> Adding bats to run docker

- TotalCrossVM/src/event/linux/event_c.h
- TotalCrossVM/src/init/tcsdl.cpp
- TotalCrossVM/src/init/tcsdl.h
- TotalCrossVM/src/nm/ui/android/skia.cpp
- TotalCrossVM/src/nm/ui/android/skia.h
Highlights:
- Changes create texture from surface to create texture with renderer
- Now texture access is by stream
- Torizon with broken icons and bad performance
> Generic implementation of SDL texture streaming + Skia

- TotalCrossSDK/src/main/java/totalcross/ui/anim/FadeAnimation.java
FadeAnimation wasn't using offscreen, causing the fade to not work.
> Fixes FadeAnimation fade not working.

- TotalCrossSDK/src/main/java/totalcross/sys/Settings.java
Forgotten Linux ARM platform addition
> Forgotten Settings.java changes (#35 issue)

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Trying to fix some configuration problem with issue templates I decide to write again, directly in totalcross repository
> Writing again issue templates

- CODE_OF_CONDUCT.md
- README.md
Improvement on readme.md:
* Add a menu like in our website;
* Fix English grammar;
* Add KnowCode link and summary;
* Add list of our non-code contributors like OW2 asks for.
Others changes:
* Add conduct code in OSS guidelines.
> Improvement on basics community documentations

- TotalCrossSDK/src/main/java/totalcross/ui/Switch.java
The bar was an image that needed to be loaded an then drawn. Instead of loading an image, I delegated the switch bar to be drawn by Graphics primitives. Also, I've disabled by default the ripple effect that cause a weird behaviour on the animation when the switch is pressed. Now the component looks better.
The bar through which the switch button slides is not being drawn on platforms that uses skia.
- Device: iOS, Android, Linux, Linux_arm (platforms that use skia to draw);
- OS: Raspberry PI OS; iOS, Android.
- adding a switch to the screen. The bar now normally appears. 
- Device: Raspberry PI 4
- OS: Raspberry PI OS
> Fixes switch bar not being drawn on platforms that use skia

- TotalCrossSDK/src/main/java/totalcross/Launcher.java
This is just a quick and dirty fix, using an auxiliary hashmap to track failed attempts of loading a font file.
Closes #80 
Launcher (Simulator)
> Launcher: avoids attempting to load a missing font file over and over

- TotalCrossSDK/src/main/java/tc/tools/AnonymousUserData.java
No longer gets UUID before asking the user about sending anonymous data.
Http operations were also moved to a secondary thread to not interfere with the Launcher.
Launcher (Simulator)
> AnonymousUserData: no longer gets UUID before asking the user

- TotalCrossVM/src/init/tcsdl.cpp
reverts previous commit for better commit history
> Revert "Avoid SDL display bounds dependency (#99)"

- .github/workflows/build.yml
Added CI build
N/A
Increase the QA in the delivery process
N/A
N/A
N/A
N/A
> cicd: added the CI build

- TotalCrossSDK/license.txt
During the license change it was forgotten and was causing problems, see #143
> license: update why was it forgotten

- TotalCrossSDK/src/main/java/totalcross/Launcher.java
- TotalCrossSDK/src/main/java/totalcross/net/ssl/SSL.java
- TotalCrossSDK/src/main/java/totalcross/net/ssl/SSLCTX.java
- TotalCrossSDK/src/main/java/totalcross/ui/media/MediaClip.java
Removes dependency on old private Sun libraries.
This is required to build the sdk using latest versions of JDK (JDK 9+?)
Need to test the following things:
> Removes dependency on old private Sun libraries.

- TotalCrossSDK/src/main/java/totalcross/lang/StringBuffer4D.java
adds missing CharSequence constructor
fixes #135
improves jdk compatibility
> stringbuffer: adds missing CharSequence constructor

- .gitlab/issue_templates/Documentation.md
- CODE_OF_CONDUCT.md
- README.md
Some docs are out of date or lack information, on the other hand, some files are also not needed.  These 4 **unrelated commits** can improve the quality of life of our repository by mitigating these problems 😅
> Repository life quality, October, 2020

- CHANGELOG.md
- TotalCrossSDK/build.gradle
- TotalCrossSDK/src/main/java/totalcross/sys/Settings.java
> Release: 6.1.1

- TotalCrossSDK/src/main/java/totalcross/Launcher.java
Support full screen mode for non-TC VMs instances. A new command line parameter is introduced which forces the UI to go to full screen.
- Fixes feature request #185
It is a requested feature
- Running TC using regular JDK instanced
> feature: implement #185

- TotalCrossSDK/src/test/java/tc/tools/AnonymousUserDataTest.java
> statistics: fix compilation error of exception not being thrown

- .github/workflows/main.yml
> cicd: fix bucket link

- TotalCrossVM/src/init/settings.c
- TotalCrossVM/src/init/settings.h
- TotalCrossVM/src/litebase/TCVMLib.c
litebase was broken since the migration for CMake
> litebase: fixes using litebase

- TotalCrossSDK/src/main/java/totalcross/ui/html/Document.java
- TotalCrossSDK/src/main/java/totalcross/util/I18N.java
- TotalCrossSDK/src/main/java/totalcross/xml/AttributeList.java
- TotalCrossSDK/src/main/java/totalcross/xml/DumpXml.java
- TotalCrossSDK/src/main/java/totalcross/xml/XmlReadableByteArray.java
- TotalCrossSDK/src/main/java/totalcross/xml/XmlReadablePort.java
- TotalCrossSDK/src/main/java/totalcross/xml/XmlReadableSocket.java
- TotalCrossSDK/src/main/java/totalcross/xml/XmlReader.java
- TotalCrossSDK/src/main/java/totalcross/xml/XmlTokenizer.java
- TotalCrossSDK/src/main/java/totalcross/xml/rpc/XmlRpcClient.java
- TotalCrossSDK/src/main/java/totalcross/xml/soap/SOAP.java
Fixes encoding on xml's parser reported on #190
> xml: fix encoding to support more characters

- .github/workflows/main.yml
Fix the issue described in #238. Every pull request for master will trigger the workflow.
> cicd: fix cyclical dependency for PRs

- .github/workflows/commit.yml
The last commit is causing problems. It is not working as expected: the commit checker is checking the content of the pull request and not the commit.
> revert: e420cb it's not working as it should

- TotalCrossSDK/src/main/java/totalcross/util/I18N.java
- TotalCrossSDK/src/main/java/totalcross/xml/XmlReadableByteArray.java
- TotalCrossSDK/src/main/java/totalcross/xml/XmlTokenizer.java
Fix build error caused by the xml encoding fix
> sdk: fix sdk build error message

- TotalCrossSDK/src/main/java/totalcross/Launcher.java
- TotalCrossSDK/src/main/java/totalcross/sys/Settings.java
Added the debug info option for the simulator
- Issue #231 
Please link the issue here.
To make the console leaner for the user
- Device:Simulator
- Enabled /dbginfo and see if the messages shown up, removed and see if they don't
-Device:Simulator 
With /dbginfo
without /dbginfo
> Added debug info option

- .github/ISSUE_TEMPLATE/bug_report.md
Update the bug report template
- The current bug report template is overcrowded without pointing out the required info needed to properly bug report.
- only totalcross team
> doc: update bug report template

- CONTRIBUTING.md
First changes:
- Answer "The 80 chars are inclusive the type?";
- Fix commit sample;
- Be explicit about the commit body.
> Contributing guidelines enhancement

- TESTING.md
Provides guidance on what needs to be tested whenever a new TotalCross version is released.
Outlines target devices, operational systems and sample applications selected for testing.
A step-by-step standard test for each application is missing.
- N/A
- N/A
- N/A
- N/A
> doc: add information on target devices OS and apps

- TotalCrossSDK/src/main/java/totalcross/xml/XmlReader.java
- TotalCrossSDK/src/main/java/totalcross/xml/soap/SOAP.java
last argument of copyOfRange is last index, and not length
> bugfix: fixes usage of Arrays.copyOfRange

- TotalCrossVM/src/nm/ui/GraphicsPrimitives_c.h
> bugfix: fixes bug with animated images introduced by 5aa70187

- TotalCrossSDK/src/main/java/totalcross/lang/String4D.java
> string: adds all String constructors with byte input and charset

- TotalCrossSDK/src/main/java/totalcross/Launcher.java
> font: removes resizing of font on simulator for better fidelity across platforms
