.gitmodules
TotalCrossVM/builders/gcc-linux-arm/docker-builder-image/Dockerfile
TotalCrossVM/builders/gcc-linux-arm/docker-builder-image/build.sh
TotalCrossVM/builders/gcc-linux-arm/tcvm/Makefile
TotalCrossVM/builders/gcc-linux-arm/tcvm/build.sh

Watching #14 we concluded that the need to change SDL linking **to dynamic**,  [FOSSA](https://app.fossa.com/)  warned us about the SDL license (GPLv3) :sleepy:.

Dynamically linking SDL

---

TotalCrossVM/src/util/posix/debug_c.h

System.out.prinft now only prints log stuff in debugConsole.txt, with these changes log will be redirect both to console.

Added printf() inside write to debugConsole.txt method

---

TotalCrossVM/src/event/linux/event_c.h
TotalCrossVM/src/init/posix/settings_c.h
TotalCrossVM/src/init/tcsdl.cpp
TotalCrossVM/src/init/tcsdl.h
TotalCrossVM/src/nm/ui/GraphicsPrimitives.h
TotalCrossVM/src/nm/ui/android/skia.cpp
TotalCrossVM/src/nm/ui/android/skia.h
TotalCrossVM/src/nm/ui/linux/gfx_Graphics_c.h
TotalCrossVM/src/nm/ui/linux/gfx_ex.h

Highlights:
- Fix Torizon/Wayland SDL initialization :satisfied: ;
- Improves how we handle Pixel Format;
- Bypass SDL_Surface;
- Better comments and function descriptions.

Fix Torizon/Wayland SDL initialization

---

TotalCrossSDK/src/main/java/totalcross/ui/Edit.java

Solve #12,  but we didn't set it by default and still don't detect if there is a keyboard connected :disappointed:

Fix showVirtualKeyboard else statement

---

TotalCrossVM/builders/gcc-linux-arm/tcvm/Makefile

This is a hack to allow extending the values used for
cross-compiling. 
When using the `=` operator, the build system can't append more options to CFLAGS  and CXXFLAGS, and for Yocto Project we need to append the cross-compile related options.
- Device: All Yocto Project machines
- OS: All Yocto Project based distros
- This has been tested in the Yocto Project builds
- Device: Apalis i.MX6DL, Colibri i.MX6DL and Colibri i.MX6ULL 
- OS: O.S. Systems Embedded Linux

make: Allow expanding CFLAGS and CXXFLAGS

---

TotalCrossSDK/src/main/java/totalcross/ui/Container.java

Problem: When using Container.setStyle(BORDER_ROUNDED), the rounded border is drawn on java side using CPU and the draw is not right on linux arm resulting in a terrible rounded rectangle draw.
Solution: now BORDER_ROUNDED is drawn using Graphics primitives fillRoundedRect and drawRoundedRect. This allows GPU to take care of this draw fixing the terrible behaviour above. The simulator side keeps the solution above because roundrect does not draw beatufil round rectangles.
When using Container.setBorderStyle(BORDER_ROUNDED), a rounded rectangle is designed representing such a container. On linux arm devices, the draw is very creepy. In addition the draw is made on the Java side using CPU.   
- this is being fix for an example
This was made to get a more beautiful draw when using rounded …

fix BORDER_ROUNDED on Container for linux arm devices

---

TotalCrossVM/src/nm/ui/font_Font.c

Font.getFont("Fonts/Roboto-Bold.ttf", false, size) leads FontMetrics.stringWidth(String s) to returns almost double of the size of the font. The reason this is happening is because on the vm side it already adds .ttf the end of the name of the font making the vm look for Fonts/Roboto-Bold.ttf.ttf instead of the originally passed argument. To solve this, I check if name of the font already comes with .ttf before concatenating .ttf to the of the name.
Wrong Label width because when using `Font.getFont("Fonts/Roboto-Bold.ttf", false, size)` instead of `Font.getFont("Fonts/Roboto-Bold", false, size)` without `.ttf`.
- Device: devices that has as OS iOS, Android and Linux/Linux_arm
- OS: iOS, Android, Linux and Linux_arm
- I took different ttf files and loaded them in a Test project. Then, for …

Fix wrong FontMetrics.stringWidth(String s) on devices that use skia

---

TotalCrossVM/src/nm/lang/Process.c
TotalCrossVM/src/nm/lang/Runtime.c
TotalCrossVM/src/nm/nio/channels/FileChannelImpl.c

Removing some C files from wince build.
Fixing this to avoid a furute issue with WinCE. 
The files removed are not compatible with WinCE build.
- Device: All Window CE devices.
- OS: Windows CE
- Running the build process for Windows CE.
- Device: USA Windows Mobile 5.0 Pocket PC T2 Emulator
- OS: Windos CE

Adding header files to HEADLESS on Runtime.c to fix build on wince.

---

TotalCrossSDK/src/main/java/totalcross/ui/image/Image.java

Describe your changes in details. 
- #27 
Solves the problem with deploying totalcross java components from api to tcz when using Java Headless.
- Device: arm devices.
- OS: for building yocto images.
- build passed by test made by OS System.
- Device: Linux ARM devices

Fix executing with JDK headless

---

TotalCrossSDK/src/main/java/totalcross/game/Animation.java

At onPaint of the class totalacross.game.Animation, there were some unnecessary printlns. This was producing some annoying and unnecessary logs.
- Device: all
- OS: all
- running it on the simulator 
- Device: Simulator
- OS: any

Removes wrong debugging on totalcross.game.Animation

---

TotalCrossSDK/src/main/java/totalcross/ui/Flick.java

The flick effect introduced on TotalCross 5.0.0 causes, when using horizontal scroll, the wrong behaviour of pulling the content back to the initial position. In order to fix it. I reverted the class Flick.java to the previous version (4.X.X). In addition, this made an noticeable improvement on the performance of the ScrollContainer component. Besides we have a less smooth scroll, at least now we have an 100% functional scroll, not beautiful, but functional!
Fixes wrong behaviour caaused by flick and improves performance of scroll. 
- Device: All
- OS: All
Two tests were performed
i) I've added an horizontal scroll with a bunch of icons on it. When flicking on the old version (5.1.4 and 6.0.4), the scroll was pulling baack to initial position. 
ii) I've put a number of Buttons (100) and …

Fixes wrong scroll behaviour on horizontal and improves scroll performance

---

TotalCrossSDK/build.gradle
TotalCrossSDK/src/main/java/tc/Deploy.java
TotalCrossSDK/src/main/java/totalcross/ui/MainWindow.java

Removes a "gambiarra" that removed sensitive code from the sources publicly available. This code is no longer is necessary, neither is the source filtering.
Some cleanup and fixing of the build.gradle file. Building should be faster and use less disk space.
This also fixes automatic IDE integration through the build.gradle file - vscode for example couldn't handle it properly because of the duplicate source files.
Removing old proprietary code and some "gambiarras" made at the time. Also fixing the vscode support to allow debugging the SDK.
Compared all the output generated by gradle using the command `gradlew clean dist -x test` before and after the changes to make sure the output is the same.
The only difference is that `InvalidateIPA` is no longer artificially removed, which is no …

java build fixes and cleanup

---

TotalCrossVM/src/launchers/linux/Launcher.c

In most systems, TotalCross uses a command line application named Launcher to start an application. This is somewhat similar to the JDK, which uses the "java" application, but unlike it, the Launcher doesn't take the application entry point as an argument, instead it assumes it was renamed to match the TCZ name of the application.
This approach requires the user to  have multiple copies of the Launcher renamed for each application, which is mildly annoying, especially when debugging.
Whenever the application being executed is named "Launcher", it checks for additional arguments and uses the first one as the name of the tcz to start the application.
This is backwards compatible because it doesn't change the original behaviour if "Launcher" is renamed and still allows the application to …

Changes Launcher to accept the actual name of the tcz as an argument.

---

TotalCrossSDK/src/main/java/totalcross/ui/dialog/keyboard/AlphabetKeyboard.java
TotalCrossSDK/src/main/java/totalcross/ui/dialog/keyboard/NumericAndSymbolsKeyboard.java
TotalCrossSDK/src/main/java/totalcross/ui/dialog/keyboard/VirtualKeyboard.java

also disables effects on buttons and changes some width and height calculations to make it less dependant on absolute values.
There's still A LOT to improve in this code.
Sliding window animation for the virtual keyboard
Make the keyboard prettier
All devices
Tested using the Launcher on the SDK

virtualkeyboard: adds a sliding animation to the keyboard

---

TotalCrossSDK/src/main/java/totalcross/json/JSONObject.java

Instead of only returning a value passed through argument on `opt##TYPE(String key, ##TYPE value)`  the methods were also throwing exceptions when the key object didn't exist in the JSONObject. To solve this, we removed all throws from these methods.
All devices

jsonobject: removes printStackTrace from opt methods

---

TotalCrossSDK/etc/tools/iOSCodesign/tccodesign.sh

Removed -x from #!/bin/bash in tccodesign.sh that produced unintentional debug on the bash script. When necessary, the user can achieve the same result by typing bash -x tccodesign.sh.
When using the user deploys and application and has to resign this application using tccodesign.sh the script procuced unintentional debug.  
- Device: Apple devices
- OS: iOS

Fix unintentional debug from tccodesign.sh

---

TotalCrossVM/src/nm/ui/GraphicsPrimitives_c.h
TotalCrossVM/src/nm/ui/android/skia.cpp
TotalCrossVM/src/nm/ui/android/skia.h

Adds alphaMask argument to skia_drawSurface for usage with SkPaint.
Problem noticed when working for #73 
Image.alphaMask allows applying an alpha value to the entire image, without individually changing the pixels.
The implementation for this feature is missing for platforms using Skia and is needed for effects like described on #73
Platforms that use Skia as graphical backend, right now:
Android, iOS, Linux x86_64 and Linux ARM.
Tested with implementation of fading between two ImageControls made for #73
MacOS (experimental build)
Raspberry Pi

Image.alphaMask: adds support for alphaMask on Skia

---

TotalCrossSDK/src/main/java/totalcross/game/AnimatedButton.java
TotalCrossSDK/src/main/java/totalcross/game/Animation.java
TotalCrossSDK/src/main/java/totalcross/game/AnimationEvent.java
TotalCrossSDK/src/main/java/totalcross/game/AnimationHandler.java
TotalCrossSDK/src/main/java/totalcross/game/GameEngine.java
TotalCrossSDK/src/main/java/totalcross/game/GameEngineException.java
TotalCrossSDK/src/main/java/totalcross/game/GameEngineMainWindow.java
TotalCrossSDK/src/main/java/totalcross/game/HighScoreEntry.java
TotalCrossSDK/src/main/java/totalcross/game/HighScores.java
TotalCrossSDK/src/main/java/totalcross/game/Options.java
TotalCrossSDK/src/main/java/totalcross/game/Sprite.java
TotalCrossSDK/src/main/java/totalcross/game/TextRenderer.java

Just removed the `@Deprecated` tags
A while ago this entire package was deprecated because it was not being updated with best practices to perform animations. We decided to take a step back and remove the deprecation status in the hopes that someone may take care of this fun lil package.
All devices.

Game: removes deprecation of this package

---

TotalCrossSDK/src/main/java/jdkcompat/io/FileInputStream4D.java
TotalCrossSDK/src/main/java/jdkcompat/io/FileOutputStream4D.java
TotalCrossSDK/src/main/java/jdkcompat/nio/channels/FileChannel4D.java
TotalCrossSDK/src/main/java/jdkcompat/nio/channels/FileChannelImpl4D.java
TotalCrossSDK/src/main/java/jdkcompat/nio/channels/spi/AbstractInterruptibleChannel4D.java
TotalCrossVM/src/init/nativeProcAddressesTC.c
TotalCrossVM/src/nm/NativeMethods.h
TotalCrossVM/src/nm/NativeMethods.txt
TotalCrossVM/src/nm/NativeMethodsPrototypes.txt
TotalCrossVM/src/nm/nio/channels/FileChannelImpl.c

AbstractInterruptibleChannel4D: Adds class with methods isOpen, close and implCloseChannel to match JDK interface.
FileChannel4D: Changes class hierarchy to extend AbstractInterruptibleChannel, matching the JDK interface more closely.
FileChannelImpl4D: Adds native method implCloseChannel, which is called by AbstractInterruptibleChannel.close to close the native file descriptor.
FileOutputStream4D: Implements finalize to close the stream, which closes the underlying FileChannel.
FileInputStream4D: Adds missing close method and implements finalize to close the stream.
Related to #70
Fixes leakage of file descriptors when using FileOutputStream/FileInputStream
Linux systems
Not tested yet
Not tested yet

FileChannel: fixes leakage of native file descriptors

---

TotalCrossVM/src/nm/NativeMethods.h

Fix error: `'tidPC_readWriteBytes_Biib' undeclared` from:
```log
error: 'tidPC_readWriteBytes_Biib' undeclared (first use in this function); did you mean 'tiPDBF_readWriteBytes_Biib'?
htPutPtr(&htNativeProcAddresses, hashCode("tidPC_readWriteBytes_Biib"), &tidPC_readWriteBytes_Biib);
```
in TCVM build process for Linux

Native methods: adds PortConnector readWriteBytes func into header

---

README.md

Just a little change in the getting started link that was named "Try in 8 minutes" and was changed to "Get Started" as it is our website.

change Try in 8 minutes to Get Started

---

.github/workflows/commit.yml

Add commit checker job and start the github actions.
- N/A
We need to check the commit before accept it.
- N/A
- Check the actions link: https://github.com/TotalCross/totalcross/actions
- N/A

cicd: starting the commit check

---

TotalCrossSDK/src/main/java/totalcross/Launcher.java

The */r* argument was the argument that referenced TotalCross's serial license number. To keep backwards compatibility, we just skipped what it would do, but we didn't do it the right way. This patch adjust the argument iterator, it has no effect when being incremented within the `if`.  Bug reported on #94.

simulator: correctly skips the key arg

---

TotalCrossVM/src/nm/io/device/gpiod/posix/gpiodLib.c

Using globfree when glob fails crashes de tcvm.
That's why having libgpiod fixed the crash.
Closes #96 
- Linux ARM systems

libgpiod: fixes crash when running on a system without libgpiod

---

TotalCrossVM/src/init/tcsdl.cpp

The functions of SDL had issues in distros like _Ångström_:
```c++
SDL_GetDisplayBounds();
```
and
```c++
SDL_GetDisplayUsableBounds();
```
and
```c++
SDL_CreateRenderer();
```
they depended on some certain workaround to run correctly on any systems. They were useful to get the size of the screens.
We now introduce 3 environment variables for execution. Since we do not have an automatic viewport they need to be set up they are:
|     | TC_WIDTH  | TC_HEIGHT  | TC_FULLSCREEN  |
|---|---|---|---|
| Description  | Size of `width` in pixels  | Size of `height` in pixels  | Is fullscreen or not  | 
| Values  |  int | int  | bool | 
In case the standard resolution is not met, it will be _640x400_. That should change soon.
I think that squash should not be done since each commit is semantically …

Avoid SDL display bounds dependency

---

TotalCrossVM/src/init/tcsdl.cpp

To improve usability in systems that do not define the `SDL_RENDER_DRIVER` environment variable, it presents a tip on how to solve!
Previous:
```bash
SDL_CreateRenderer failed: Couldn't find matching render driver
```
Next:
```bash
SDL_CreateRenderer failed: Couldn't find matching render driver
HINT: try fill SDL_RENDER_DRIVER environment variable with an available render driver!
```

Shows hint to help if get error in CreateRenderer

---

TotalCrossSDK/src/main/java/totalcross/lang/Double4D.java

fix floating pointer operations that cannot be padded
application of code style added padding before and after operators, which caused and error in a java file

codestyle: fix floating pointer operations that cannot be padded

---

scripts/format-source-code

The script allow for easy run of the script when developing the code. We
can run it from the root source directory or inside the scripts
directory.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

scripts: format-source-code: Add script for Unix use

---

TotalCrossVM/modules/skia/include/private/SkTemplates.h

The following error was identified in the build:
```bash
[ 97%] Building C object CMakeFiles/tcvm.dir/src/litebase/parser/SQLInsertStatement.c.o
[ 98%] Building C object CMakeFiles/tcvm.dir/src/litebase/parser/SQLSelectStatement.c.o
[ 98%] Building C object CMakeFiles/tcvm.dir/src/litebase/parser/SQLUpdateStatement.c.o
[ 99%] Building CXX object CMakeFiles/tcvm.dir/src/nm/ui/android/skia.cpp.o
In file included from /home/allan/TotalCross/sdk-public/TotalCrossVM/src/nm/ui/android/skia.cpp:37:
In file included from /home/allan/TotalCross/sdk-public/TotalCrossVM/modules/skia/include/core/SkPathEffect.h:12:
In file included from /home/allan/TotalCross/sdk-public/TotalCrossVM/modules/skia/include/core/SkPath.h:22:
In file included from …
```

Fix arrow operator end EOL

---

TotalCrossVM/src/init/tcsdl.cpp

The implementation of output and error was in the C standard, as we are talking about a C ++ file it makes sense to leave them in the language standard.

SDL: improve IO messages

---

CHANGELOG.md

changelog sections from 6.1.0 have titles greater than the ones made on
previous versions. This change sizes to be according to the older changelogs.

changelog: fix 6.1.0 section titles sizes

---

TotalCrossVM/docker/arm32v7/Dockerfile

For the reason that many users still use Angstrom to make a first test
of their applications, even though it is deprecated,  these changes
rollback static linking of sdl2 on libtcvm.so for armv7 to make our vm
runnable again without any extra work. 
For aN easier first try on Angstrom OS. Angstrom doesn't come with sdl2, so this change statically links sdl2 in order to make TotalCross totally functioning on this distribution without any extra work of recompiling this distro with any required dependences. 
- Device: Linux arm
- OS: Angstrom, Raspberry OS
- It was tested on Angstrom and Raspberry OS by running the TCSample applicaation with the built libtcvm.so
- Device: Raspberry PI 4 and Toradex Colibri IMX6ULL. 
- OS: [e.g. Linux Raspbian 10]

sdl: bring back static linking for sdl2 on target armv7

---

TotalCrossVM/src/init/tcsdl.cpp

Place a declaration of the size variables closest to its use to resume the implementation of `SDL_DisplayBouns `/ `SDL_WINDOW_RESIZABLE` / Window from GTK

sdl: sizes and fullscreen update

---

TotalCrossSDK/src/main/java/totalcross/net/ssl/SSLSocketFactory.java

Should always yields a `SSLSocket` when in `SSLSocketFactory`. As
`SSLSocketFactory` extends `SocketFactory` and does not override the
`createSocket(String, int)` method, and calls from super classe. As
`SocketFactory` yields plain sockets...
This fix just delegates to `createSocket(String, int, int)` passing the default
`Socket.DEFAULT_OPEN_TIMEOUT` as the open timeout argument. Maybe it should be
better to call `new SSLSocket(String, int)`, but this constructor does not
exists yet.
- Solves #101
Creates a SSLSocket from a SSLSocketFactory implying the default open timeout.
TC-SDK as a whole, also Java
- By writing a merge request to https://gitlab.com/geosales-open-source/tc-http-conn/develop to let it be able to deal with HTTPS.
- this MR indeed …

api: change `SSLSocketFactory` to always yield a `SSLSocket`

---

TotalCrossVM/src/init/tcsdl.cpp

The previous commits introduce the `flags` variable, but it was unused. This variable is very important to open TC in window mode without window size issues.

sdl: use `flags` to adjust window sizes

---

TotalCrossVM/docker/arm64/Dockerfile
TotalCrossVM/docker/arm64/build-docker.sh
TotalCrossVM/docker/arm64/cmake.sh

- adds Dockerfile and script to create the container for building the libtcvm
- adds precompiled static library libskia.a for archtecture arm64 (aarch64)
- adds script cmake.sh that builds the libtcvm.
⚠️  **Please notice** that PNG_ARM_NEON_OPT must be disabled when building for arm64, because NEON instructions are not supported by qemu yet. This is done by passing the argument PNG_ARM_NEON_OPT=0 when executing cmake.
#137 
Building also for linux-arm64 is required to support iMX8 modules.
- Any device with arm64 architecture running Linux
- Toradex iMX8 using yocto image built in house
TODO

arm64: adds support for building to arm64 using docker

---

TotalCrossVM/src/event/linux/event_c.h

isEventAvailable is executed before pumpEvent, there's no need for calling it twice
I was looking for ways to improve graphical performance and noticed this redundant call.
- Linux systems
- iMX6ULL

sdl: event: linux: removes redundant code

---

TotalCrossSDK/build.gradle

We can finally run JUnit Tests on our SDK 
Unit Testing is an essential step on the development process. It provides code quality and avoids bug regression. 
- Intelij;
- command line (`cd TotalCrossSDK; ./gradlew test`);
- VSCode.
I didn't figure out how make it work on VSCode. However, on Intelij and by executing command `./gradlew test` it is working just fine.
Follow the steps bellow to learn how to test and debug on Intelij.
1) open the folder `tc_repository/TotalCrossSDK`;
2 ) Create a Gradle Run/Debug Configuration called test and add `test` to the field `Tasks`:
3) Click on the play button to run the tests;
4) You can also debug testing by clicking on the bug button near the play button:

test: add JUnit 5 test engine to TC SDK build

---

TotalCrossSDK/build.gradle

update appdirs library from 1.0.0 to 1.2.0 to avoid the
following bug:
https://github.com/harawata/appdirs/issues/2
```
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/Shell32    
at net.harawata.appdirs.impl.ShellFolderResolver.resolveFolder(ShellFolderResolver.java:38)  
at net.harawata.appdirs.impl.WindowsAppDirs.getLocalAppData(WindowsAppDirs.java:71)
at net.harawata.appdirs.impl.WindowsAppDirs.getUserDataDir(WindowsAppDirs.java:33)
at net.harawata.appdirs.impl.WindowsAppDirs.getUserConfigDir(WindowsAppDirs.java:40)
at net.harawata.appdirs.AppDirs.getUserConfigDir(AppDirs.java:36)
at tc.tools.AnonymousUserData.<clinit>(AnonymousUserData.java:43)
at totalcross.Launcher.lambda$parseArguments$0(Launcher.java:471)
at …
```

build: update appdirs to avoid bug on Windows

---

TotalCrossSDK/src/main/java/tc/Deploy.java
TotalCrossSDK/src/main/java/tc/tools/AnonymousUserData.java
TotalCrossSDK/src/main/java/totalcross/Launcher.java
TotalCrossSDK/src/test/java/tc/tools/AnonymousUserDataTest.java

Class AnonymousDataUser was producing unexpected uuid's and registering deploy and launches without complete data. Some of the reasons are: i) it was storing user uuid as userUuid, differently than the vs code plugin the stores "uuid"; ii) short timeout time causing the token to be generated but not read; iii) #83 and #146 might be related with producing a way more users than the naturally should do, because token were being generated but not stored.
- Unit tests;
- integration tests;
- this PR depends on #83 must be draft until #83 is closed.

Fix class AnonymousDataUser producing wrong data

---

TotalCrossVM/src/nm/ui/GraphicsPrimitives_c.h
TotalCrossVM/src/nm/ui/image_Image.c

fixes lockChanges, by changing applyChanges and drawSurface to use
the changed field to avoid texture recreation
#182
Platforms that use Skia
Tested on Linux devices - should have no side effects.

image: using lockChanges now correctly prevents texture recreation

---

TotalCrossSDK/src/main/java/totalcross/ui/FloatingLabel.java

There was a memory aggression, when using FloatingLabel. A runaway argument preventing proper animation, which lead to the font to grow forever. This patch bounds the size of the font used and prevents from this memory leak.
Fix issue #124 
- All devices
- Used the DashBoard sample and the simulator
- applied on master version
- Device: Mac
- OS: macOS 10.15.5

bugfix #124: no upscaling of font, fixing memory consumption

---

TotalCrossSDK/src/main/java/totalcross/ui/dialog/keyboard/AlphabetKeyboard.java

Fix the double PEN_UP issue on keyboard. The problem was with the ripple effect; when the effect was  forcibly removed, the keyboard produced double events.
Reintroduction of the ripple effect solves the issue but we might need to find a way to safely disable it, if on low end devices this is a problem
Issue #184 
- Any device that has onscreen keyboard
- On the emulator

bugfix: fixing issue #184

---

TotalCrossVM/CMakeLists.txt
TotalCrossVM/src/nm/io/device/gpiod/posix/gpiodLib.c
TotalCrossVM/src/nm/ui/android/skia.cpp

Many build tools and toolchains use newer versions of GLIBC. This was causing problems on some systems including the Raspberry Pi.

build: make libtcvm compatible with glibc 2.16+ (previously 2.27+)

---

.github/workflows/commit.yml

Fix the issue described in #238. Workflow overlooked in previous commit. Now commits will only be analyzed on pull requests (it makes more sense).

cicd: fix cyclical dependency for PRs (commit checker)

---

TotalCrossVM/CMakeLists.txt
TotalCrossVM/src/nm/io/device/gpiod/posix/gpiodLib.c
TotalCrossVM/src/nm/ui/android/skia.cpp

Solve error that occurs after new skia version
```log
libtcvm.so: 
No symbol version section for versioned symbol `expf@GLIBC_2.4'
```

build: fix glibc build error

---

.github/workflows/main.yml

Now all workflows can fail or succeed. Before, if any of the linux builds failed to build the SDK and Android it would be skipped.

cicd: do not skip the SDK build if the previous build fails

---

.github/workflows/main.yml

Now use DockerHub containers. See `TotalCross/totaldocker`. Adjust some paths.

cicd: do not build the containers anymore

---

TotalCrossSDK/src/main/java/totalcross/ui/dialog/MessageBox.java

Fix Message title in non-Material UI
Issue #177 
- Emulator
- In devices with the help of @VicMisael

bugfix: fix issue #177

---

.github/workflows/package.yml

Some files still had to be obtained, and that didn't make any sense. Closes #235.

cicd: copy *.jar files because we need them to release versions

---

.gitignore

Better support JetBrain families of IDEs
TotalCrossSDK under JetBrain's IDEs left some garbage which needs to be ignored

feature: bette support jetbrain

---

.github/workflows/package.yml

Sometimes, we need to build everything without having to merge commits. Just add button to start workflow manually.

cicd: allow manual trigger for package workflow

---

TotalCrossSDK/src/main/java/tc/Deploy.java
TotalCrossSDK/src/main/java/tc/tools/deployer/Deployer4LinuxArm64.java

Adding Linux ARM 64 to linux_arm platform deploy, this will deploy both linux_arm and linux_arm64 when deploying for linux_arm.

deploy: add Linux ARM 64 to linux_arm platform deploy

---

.github/workflows/release.yml

The release workflow would generate errors because the workflow file is wrong.

cicd: change last artifacts workflow

---

TotalCrossSDK/src/main/java/jdkcompat/util/Objects4D.java

Changing Objects to Objects4D and change packate to jdkcompat.util instead of totalcross.util to fix on bug when using java.util.Objects. Related to #276

objects: fix to properly call Objects4D when using jata.util.Objects

---

TotalCrossVM/src/init/tcsdl.cpp

Using SDL_VideoInit and SDL_VideoQuit just to test the available video
drivers causes a segfault during SDL_Init on some systems.
fixes #263 and possibly #265 as well

sdl: fixes segfault during SDL initialization

---

TotalCrossVM/src/init/tcsdl.cpp

Some devices crash when opengl is used, so for now,
we'll force the usage of the software renderer until we
find a way to test for hardware accelerated graphics
support without crashing.
probably fixes #259

sdl: force usage of software renderer for linux arm

---

TotalCrossVM/src/event/linux/event_c.h
TotalCrossVM/src/init/tcsdl.cpp
TotalCrossVM/src/init/tcsdl.h

The SDL_Surface structure may be invalidated after a window
size changed event. On most devices the surface is still valid
after this event if the actual width and height values aren't changed.
(I have no idea why this event is raised if the actual values are the
same, but this seems to happen at least once after the initialization).
It's important to notice that the actual pointer to the screen pixels
referenced by surface->pixels DOES NOT change when the surface
is refreshed. So it's safe for us to keep using it directly with Skia.
To make sure it works for any device, SDL_GetWindowSurface
must be executed after this event to make sure the internal surface
structure kept by window is refreshed, even if we don't actually
use the new surface anywhere after. ¯\_(ツ)_/¯

sdl: fixes screen not updating after the window size is changed

---

TotalCrossVM/android/app/src/main/AndroidManifest.xml

starting from target-sdk 29 application should use scoped storage
https://developer.android.com/training/data-storage#scoped-storage

bugfix: fixes permission for writing on storage for android-29

---

TotalCrossVM/android/app/build.gradle
TotalCrossVM/android/settings.gradle
TotalCrossVM/android/tcvm/build.gradle
TotalCrossVM/android/tcvm/src/main/AndroidManifest.xml

Reduces the build time by compiling the libtcvm only twice, for armv7 and arm64, instead of 6 times. (those 2 tagets * 3 gradle flavors)

android: improves build by moving libtcvm to its own gradle target

---

.github/workflows/merge.yml
.github/workflows/package.yml

cmake builds for debugging by default, we must specify build type as release

cicd: build linux targets in release mode

---

TotalCrossVM/CMakeLists.txt
TotalCrossVM/src/nm/ui/GraphicsPrimitives.h
TotalCrossVM/src/nm/ui/PalmFont_c.h
TotalCrossVM/src/nm/ui/font_Font.c
TotalCrossVM/src/nm/ui/gfx_Graphics.c
TotalCrossVM/src/nm/ui/image_Image.c
TotalCrossVM/src/nm/ui/linux/gfx_Graphics_c.h

New feature to build TCVM without Skia. 
It's possible to generate a very little final libtcvm (~3MB on Linux). 
It's also now possible to test the VM on OpenBSD.
Able to use TCVM on OpenBSD.
- OS: OpenBSD 6.8
- OS: Linux Debian 10

Feature: option to build tcvm without Skia
